version: "3.7"

networks:
  3pbrasil-net:
    external: true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 3pbrasil-zookeeper
    networks:
      - 3pbrasil-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 15s
      retries: 3
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: 3pbrasil-kafka
    depends_on:
      - zookeeper
    networks:
      - 3pbrasil-net
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      timeout: 15s
      retries: 3
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: 3pbrasil-kafka-manager
    ports:
      - 9000:9000
    networks:
      - 3pbrasil-net
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  kong-migrations:
    image: "kong:2.3.2-alpine"
    container_name: 3pbrasil-kong-migrations
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      - database_infra
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong_db
      KONG_PG_HOST: database_infra
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: postgres
    networks:
      - 3pbrasil-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    image: "kong:2.3.2-alpine"
    container_name: 3pbrasil-kong
    user: "kong"
    depends_on:
      - database_infra
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_CASSANDRA_CONTACT_POINTS: database_infra
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong_db
      KONG_PG_HOST: database_infra
      KONG_PG_USER: postgres
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD: postgres

    networks:
      - 3pbrasil-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  database_infra:
    image: postgres:9.5
    container_name: 3pbrasil-infra-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kongs_db"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - 3pbrasil-net
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  konga-prepare:
    container_name: 3pbrasil-konga-prepare
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://postgres:postgres@database_infra:5432/konga_db"
    networks:
      - 3pbrasil-net
    restart: on-failure
    depends_on:
      - database_infra

  konga:
    container_name: 3pbrasil-konga
    image: pantsel/konga:latest
    restart: always
    networks:
      - 3pbrasil-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: database_infra
      DB_USER: postgres
      DB_PASSWORD: postgres
      TOKEN_SECRET: ahfdjgjgf79JKLFHJKh978953kgdfjkl
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
      - database_infra
    ports:
      - "1337:1337"
